import type { Metadata } from 'next';
import { IBM_Plex_Mono } from 'next/font/google';
import './globals.css';
import { Providers } from '@/components/Providers';
import { AppShell } from '@/components/shell/AppShell';
import { Footer } from '@/components/Footer';
import { Ticker } from '@/components/Ticker';

/**
 * Terminal design system: IBM Plex Mono everywhere. One family, four weights —
 * hierarchy comes from size, case, tracking, and color, not typeface changes.
 */
const mono = IBM_Plex_Mono({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-mono',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'PitBosses',
  description:
    'Buy a Boss. Work the Pit. Be the House. Rewards are promotional, not dividends. A permissionless front end by PitBoss Labs.',
  // OG/Twitter card: 1200x630 center crop of the banner, nothing else.
  // Icons: center Boss face. All generated by scripts/hero-crops.mjs.
  openGraph: {
    title: 'PitBosses — Run the floor. Get paid in stock.',
    description: 'The floor where every fee pays the Bosses — in real stock.',
    images: [{ url: '/hero/og.png', width: 1200, height: 630 }],
  },
  twitter: {
    card: 'summary_large_image',
    images: ['/hero/og.png'],
  },
  icons: {
    icon: [
      { url: '/brand/icon-32.png', sizes: '32x32', type: 'image/png' },
      { url: '/brand/icon-192.png', sizes: '192x192', type: 'image/png' },
      { url: '/brand/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: [{ url: '/brand/icon-180.png', sizes: '180x180', type: 'image/png' }],
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={mono.variable}>
      <body className="min-h-screen text-paper antialiased">
        <Providers>
          <AppShell>
            {children}
            <Footer />
          </AppShell>
          <Ticker />
        </Providers>
      </body>
    </html>
  );
}
